/**
 * Template for sheet questions with key, label and source tracking
 */
export interface Question {
  key: string;
  label: string;
  answer: string;
  source: 'LLM' | 'user' | 'import' | '';
}

/**
 * Static list of questions extracted from the JSON
 */
export const QUESTIONS: Array<Omit<Question, 'answer' | 'source'>> = [

  { key: "C_SUPPLIERLEGALLABEL", label: "Legal Label Description" },
  { key: "C_SUPPLIERINGRSTMT", label: "Ingredient Statement" },
  { key: "C_SUPPIERITEMNMBR", label: "Supplier Item Number" },
  { key: "C_FLAVORDESC", label: "Flavor Description" },
  { key: "C_AROMA", label: "Aroma" },
  { key: "C_APPEARANCE", label: "Appearance" },
  { key: "C_COLOR_NCISENSORYTXT", label: "Color" },
  { key: "C_PHY_BODY_TEXTURE", label: "Body and Texture" },
  { key: "BROKER", label: "Are  you a Broker Y/N" },
  { key: "PACKED_COUNTRY_OR", label: "Identifies the country where the item is packed or produced" },
  { key: "FLAVOR_SOURCE\n\nTarget-12d455b46949", label: "If flavors are used, select the flavor source (natural, artificial or natural and artificial)" },
  { key: "ENZYME_SOURCE", label: "If enzymes are used, select the enzyme source (microbiological, animal or plant)" },
  { key: "STARCH_SOURCE", label: "If starch(es) are used, select the source of starch(es)" },
  { key: "HAZARDOUS_MTL", label: "Is the raw material considered hazardous and need special handling? (y/n)" },
  { key: "READY_TO_EAT", label: "This item is ready to eat? (y/n)" },
  { key: "MICRO_RED_TREAT", label: "Identify the treatment used to reduce the microbial load of this product" },
  { key: "FS_ADD_PROCESSING", label: "Does this item need additional processing to address chemical or physical  hazards? (y/n)" },
  { key: "C_RECYLINGINSTR", label: "Recycling Instructions" },
  { key: "C_STORAGEINSTR", label: "Storage Instructions" },
  { key: "C_PKGMARKINGS", label: "Marking on Package and/ Container" },
  { key: "C_PKGWARNINGCAUTION", label: "Caution/Warning on Packag and/or Container" },
  { key: "C_CODE_EXPLANATION", label: "Code Explanation" },
  { key: "Item Line (%min and % max, COO, and Function)", label: "Range Formula" },
  { key: "Form/Extracted From , and Additive Number, and Size or Concentration Rate", label: "Range Formula" },
  { key: "RM_DAIRY", label: "NEW - Does your product contain any dairy? y/n" },
  { key: "C_SUPPLIERADDITIVE", label: "Does this item contain any incidental additives or processing aids" },
  { key: "C_SUPPLR_ADDTVCNTRL", label: "Are controls in place such that there would be no other unlabeled additives in this item, besides those indicated?" },
  { key: "SHIP_TEMP_RANGE", label: "Identifies the range of temperature within which an item should be shipped" },
  { key: "STORAGE_TEMP_RANGE", label: "Identifies the range of temperature within which an item should be stored" },
  { key: "SHELF_LIFE - MAPPED to GUARANTEE", label: "Identifies the expected shelf life - unopened" },
  { key: "SHELFLIFE_OPEN", label: "Shelf life of product after package has been opened" },
  { key: "LEAD_TIME", label: "Lead time in days" },
  { key: "MIN_ORDER_QTY", label: "Minimum order quantity in pounds" },
  { key: "DENSITY_2", label: "Density  (Lb/Gal_Us)" },
  { key: "SCOVILLE_UNITS", label: "Scoville units - measurement of flavor heat level" },
  { key: "PARTICLE_SZ_ON", label: "The amount of particles retained on a specific mesh size" },
  { key: "PARTICLE_SZ_THRU", label: "The amount of particles that passed thru a specific mesh size" },
  { key: "SIEVE_SIZE_ON", label: "Sieve size used to measure the particle size retained on the mesh" },
  { key: "SIEVE_SIZE_THRU", label: "Sieve size used to measure the particle size passed thru the mesh" },
  { key: "PIECE_SIZE", label: "Particulate size in inches" },
  { key: "PIECE_RETENTION", label: "Amount (%) of particles retained after rinsing with water (wet weight basis)" },
  { key: "SPECIFIC_GRAVITY", label: "Specific gravity" },
  { key: "SUGAR_BRIX", label: "Brix - measurement of sugar level" },
  { key: "VISCOSITY1", label: "Viscosity" },
  { key: "VISCOSITY_METHOD", label: "NEW QUESTION - Viscosity method" },
  { key: "VISCOSITY_TIME", label: "NEW QUESTION - Viscosity Time in seconds" },
  { key: "VISCOSITY_TEMP", label: "NEW QUESTION - Viscosity Temp F" },
  { key: "PKG_CONTAINER_TYPE", label: "Describes the package type" },
  { key: "PACKAGING_MATERIAL", label: "Identifies the make up of the packaging material" },
  { key: "PALLET_HOOD", label: "Is the item palletized with a pallet hood? (y/n)" },
  { key: "PALLET_SHRINK_WRAP", label: "Is the item palletized with shrink wrap? (y/n)" },
  { key: "PALLET_SLIP_SHEET", label: "Is the item palletized with a slip sheet? (y/n)" },
  { key: "SHIP_CTNR_GROSS_WGT", label: "Total gross weight of the ship container (including product and packaging materials)" },
  { key: "SHIP_CTNR_NET_WEIGHT", label: "Net weight of product in a ship container (not including any packaging materials)" },
  { key: "SHIP_CTNR_PER_LAYER", label: "Number of ship containers per pallet layer" },
  { key: "SHIP_CTNR_PER_PALLET", label: "Number of ship containers per pallet" },
  { key: "SHIP_CTNR_LENGTH", label: "Length target of a ship container" },
  { key: "SHIP_CTNR_WIDTH", label: "Width target of a ship container" },
  { key: "SHIP_CTNR_HEIGHT", label: "Height target of a ship container" },
  { key: "ALLERGEN_CRUSTACEA", label: "Allergen crustacean / shellfish present? (y/n)" },
  { key: "ALLERGEN_CRUSTC_PISL", label: "Crustacean shellfish present in any item manufactured on same line" },
  { key: "ALLERGEN_CRUSTCA_PIF", label: "Crustacean shellfish present in same manufacturing facility" },
  { key: "ALLERGEN_EGG", label: "Allergen egg present? (y/n)" },
  { key: "ALLERGEN_EGG_PISL", label: "Egg products or egg present in any item manufactured on the same line" },
  { key: "ALLERGEN_EGG_PIF", label: "Egg products or egg derivatives present in same manufacturing facility" },
  { key: "ALLERGEN_FISH", label: "Allergen fish present? (y/n)" },
  { key: "ALLERGEN_FISH_PISL", label: "Fish present in any item manufactured on the same line" },
  { key: "ALLERGEN_FISH_PIF", label: "Fish present in same manufacturing facility" },
  { key: "ALLERGEN_DAIRY", label: "Allergen dairy present? (y/n)" },
  { key: "ALLERGEN_DAIRY_PISL", label: "Dairy products or dairy derivatives present in any item manufactured on the same line" },
  { key: "ALLERGEN_DAIRY_PIF", label: "Dairy products or dairy derivatives present in same manufacturing facility" },
  { key: "ALLERGEN_PEANUTS", label: "Allergen peanuts present? (y/n)" },
  { key: "ALLERGEN_PEANUT_PISL", label: "Peanuts present in any item manufactured on the same line" },
  { key: "ALLERGEN_PEANUTS_PIF", label: "Peanuts present in same manufacturing facility" },
  { key: "ALLERGEN_SESAME", label: "Allergen sesame seeds or derivatives present? (y/n)" },
  { key: "ALLERGEN_SESAME_PIF", label: "Sesame seeds or derivatives present in same manufacturing facility? (y/n)" },
  { key: "ALLERGEN_SESAME_PISL", label: "Sesame seeds or derivatives present in any item manufactured on the same line? (y/n)" },
  { key: "ALLERGEN_SOYBEANS", label: "Allergen soybean present? (y/n)" },
  { key: "ALLERGEN_SOYPRO_PISL", label: "Soy products & hydrolysates present in any item manufactured on same line" },
  { key: "ALLERGEN_SOYPROD_PIF", label: "Soy products & hydrolysates present in same manufacturing facility" },
  { key: "ALLERGEN_TREENUT", label: "Allergen treenut present? (y/n)" },
  { key: "ALLERGEN_TREENU_PISL", label: "Treenut or treenut derivatives (includes coconut) present in any item manufactured on the same line" },
  { key: "ALLERGEN_TREENUT_PIF", label: "Treenut or nut derivatives (includes coconut and/or coconut oil) present in the same manufacturing facility" },
  { key: "ALLERGEN_WHEAT", label: "Allergen wheat present? (y/n)" },
  { key: "ALLERGEN_WHEAT_PISL", label: "Wheat products and hydrolysates present in any item manufactured on same line" },
  { key: "ALLERGEN_WHEAT_PIF", label: "Wheat products and hydrolysates present in same manufacturing facility" },
  { key: "SENS_APPLE", label: "Apple present? (y/n)" },
  { key: "SENS_COLOR_ART", label: "Artificial color present (certificated colors)? (y/n)" },
  { key: "SENS_COLORS_NATURAL", label: "Natural color present? No certificated colors (i.e. annatto, beet juice, turmeric) (y/n)" },
  { key: "SENS_SWEETNER_ART", label: "Artificial sweetener present? (y/n)" },
  { key: "SENS_BEEF", label: "Beef or beef derivatives present? (y/n)" },
  { key: "SENS_BEET_SUGAR", label: "Beet sugar present? (y/n)" },
  { key: "SENS_CELERY", label: "Celery present – roots, leaves, stalks, seeds? (y/n)" },
  { key: "SENS_CHOCOLATE", label: "Chocolate and / or chocolate derivatives present? (y/n)" },
  { key: "SENS_CORN", label: "Corn or corn derivatives present? (y/n)" },
  { key: "SENS_GARLIC", label: "Garlic or garlic derivatives present? (y/n)" },
  { key: "SENS_GLUTEN", label: "Gluten (from wheat, spelt, kamut, tritcale, oats, rye and / or barley) present? (y/n)" },
  { key: "SENS_GLUTEN_PIF", label: "Gluten present in same manufacturing facility?" },
  { key: "SENS_GLUTEN_PISL", label: "Gluten present in any item manufactured on same line?" },
  { key: "SENS_GLUTEN_HYDROLY", label: "Do any ingredients used to make this product (including growth media and substrates) contain gluten?" },
  { key: "SENS_GLUTEN_DISTILLE", label: "If gluten was present as an ingredient, was distillation used to remove any residual protein?" },
  { key: "SENS_MSG", label: "Monosodium glutamate added? (y/n)" },
  { key: "SENS_SYN_BIO", label: "Are synthetically modified organisms intentionally added? (y/n)" },
  { key: "SENS_PRESERVATIVES", label: "Preservatives or antioxidants present? (y/n)" },
  { key: "SENS_PRSRV_INCID", label: "Are incidental preservatives or antioxidants present? Y/N (These additives may be present from cross contact or be ingredients within ingredients etc. but have no technical or functional effect)." },
  { key: "SENS_PORK", label: "Pork derivatives present? (y/n)" },
  { key: "SENS_SEEDS", label: "Seed or seed derivatives present? (y/n)" },
  { key: "SENS_MUSHROOM", label: "Are mushrooms present? (y/n)" },
  { key: "SENS_TBHQ", label: "Is TBHQ (used as a preservative for vegetable oils and edible animal fats) present? (y/n)" },
  { key: "SENS_YEAST_DERIV", label: "Yeast and / or yeast derivatives present? (y/n)" },
  { key: "SENS_HERB_SPICE", label: "Are herb or spices present? (y/n)" },
  { key: "SENS_LUPINE", label: "Lupine or lupine derivatives present? (y/n)" },
  { key: "SENS_PART_HYDR_OIL", label: "Any partially hydrogenated oils present? (y/n)" },
  { key: "SENS_RENNET", label: "Rennet present? (y/n)" },
  { key: "SENS_NANO", label: "Nanotech Materials Intentionally added or made approx. size 1-100nm? (y/n)" },
  { key: "POTASSIUM_SORBATE_FR", label: "Potassium sorbate present?  (y/n)" },
  { key: "SENS_BUCKWHEAT", label: "Buckwheat or buckwheat derivatives present? (y/n)" },
  { key: "SENS_MUSTARD", label: "Mustard or mustard derivatives present? (y/n)" },
  { key: "SENS_BEE_POLLEN", label: "Bee Pollen/Propolis present? (y/n)" },
  { key: "SENS_ROYAL_JELLY", label: "Royal Jelly present? (y/n)" },
  { key: "SENS_MANGO", label: "Mango present? (y/n)" },
  { key: "SENS_PEACH", label: "Peach present? (y/n)" },
  { key: "SENS_TOMATO", label: "Tomato present? (y/n)" },
  { key: "SENS_LATEX", label: "Latex (natural rubber) present? (y/n)" },
  { key: "SENS_ORANGE", label: "Oranges present? (y/n)" },
  { key: "SENS_KIWI_FRUIT", label: "Kiwi Fruit present? (y/n)" },
  { key: "SNES_CHICKEN", label: "Chicken present? (y/n) --- Poultry or poultry derivatives present? (y/n)" },
  { key: "SENS_BANANA", label: "Banana present? (y/n)" },
  { key: "SENS_YAMS", label: "Yams present? (y/n)" },
  { key: "SENS_GELATIN", label: "Gelatin present? (y/n)" },
  { key: "SENS_PALM_OIL", label: "Palm oil or Palm oil derivatives present? (y/n)" },
  { key: "ADTV_BHA", label: "BHA (butylated hydroxyanisole) present? (y/n)" },
  { key: "ADTV_BHT", label: "BHT (butylated hydroxytoluene) present? (y/n)" },
  { key: "ADTV_TOCOPHEROL_NAT", label: "Natural tocopherol present? (y/n)" },
  { key: "ADTV_TOCOPHEROL_SYNT", label: "Synthetic tocopherol present? (y/n)" },
  { key: "SENS_SULFITE", label: "Sulfites, sulfur dioxide, sodium (bi)-sulfate present? (y/n)" },
  { key: "CALORIES", label: "Calories per 100g  - no rounding" },
  { key: "FATS", label: "Total fat value per 100g - no rounding" },
  { key: "FATS_SAT", label: "Saturated fat value per 100g - no rounding" },
  { key: "FATS_TRANS", label: "Trans fat value per 100g - no rounding" },
  { key: "FATS_POLYUNSAT", label: "Polyunsaturated fat value per 100g - no rounding" },
  { key: "FATS_MONOUNSAT", label: "Monounsaturated fat value per 100g - no rounding" },
  { key: "CHOLESTEROL", label: "Cholesterol value per 100g - no rounding" },
  { key: "SODIUM", label: "Sodium value per 100g - no rounding" },
  { key: "CARBOHYDRATES", label: "Total carbohydrates value per 100g - no rounding" },
  { key: "FIBER_NEW", label: "NEW - Dietary fiber (basis new definition) value per 100g – no rounding" },
  { key: "FIBER_SOLUBLE", label: "Soluble fiber value per 100g - no rounding" },
  { key: "FIBER_INSOLUBLE", label: "Insoluble fiber value per 100g - no rounding" },
  { key: "SUGARS", label: "Sugars value per 100g - no rounding" },
  { key: "SUGAR_ADD", label: "NEW - Added Sugars  value per 100g" },
  { key: "SUGAR_ALCOHOL", label: "Sugar alcohol per 100g - no rounding" },
  { key: "CARBOHYDRATES_OTHER", label: "Other carbohydrate value per 100g - no rounding" },
  { key: "PROTEIN", label: "Protein value per 100g - no rounding" },
  { key: "VIT_D_MCG", label: "NEW - Vitamin D value per 100g (mcg) - no rounding" },
  { key: "CALCIUM", label: "Calcium value per 100g - no rounding" },
  { key: "IRON", label: "Iron value per 100g - no rounding" },
  { key: "POTASSIUM", label: "Potassium value per 100g - no rounding" },
  { key: "VIT_A_MCG", label: "NEW - Vitamin A value retinol activity equivalents per 100g - no rounding" },
  { key: "VIT_C", label: "Vitamin C value per 100g - no rounding" },
  { key: "VIT_E", label: "Vitamin E value per 100g - no rounding" },
  { key: "VIT_E_MG", label: "NEW - Vitamin E value per 100g (mg) - no rounding" },
  { key: "THIAMIN", label: "Thiamin value per 100g - no rounding" },
  { key: "RIBOFLAVIN", label: "Riboflavin (vitamin B2) value per 100g - no rounding" },
  { key: "NIACIN", label: "Niacin value per 100g - no rounding" },
  { key: "VIT_B6", label: "Vitamin B6 (pyridoxine) value per 100g - no rounding" },
  { key: "FOLIC_ACID_NEW", label: "NEW - Folate DFE (folate, folic acid) value per 100g – no rounding" },
  { key: "VIT_B12", label: "Vitamin B12 value per 100g - no rounding" },
  { key: "BIOTIN", label: "Biotin value per 100g - no rounding" },
  { key: "PANTOTHENIC_ACID", label: "Pantothenic acid value per 100g - no rounding" },
  { key: "PHOSPHORUS", label: "Phosphorus value per 100g - no rounding" },
  { key: "IODINE", label: "Iodine value per 100g - no rounding" },
  { key: "MAGNESIUM", label: "Magnesium value per 100g - no rounding" },
  { key: "ZN", label: "Zinc value per 100g - no rounding" },
  { key: "COPPER", label: "Copper value per 100g - no rounding" },
  { key: "MANGANESE", label: "Manganese value per 100g - no rounding" },
  { key: "MOISTURE", label: "Moisture content" },
  { key: "NATAMYCIN", label: "Natamycin" },
  { key: "PH", label: "pH - measure of acidity or basicity" },
  { key: "SALT", label: "Salt content" },
  { key: "SOLIDS", label: "Total solids content" },
  { key: "SOLIDS_CORN_SYRUP", label: "Corn syrup solids content" },
  { key: "SOLIDS_H_FRUCTOSE_CS", label: "High fructose corn syrup solids content" },
  { key: "SUCROSE", label: "Sucrose content" },
  { key: "SUCROSE_EQUIVALENT", label: "Sucrose equivalent content" },
  { key: "RM_MICRO_REQ", label: "Can you meet Microbiological specifications - y/n" },
  { key: "KOSHER_CERT", label: "Kosher certification? (y/n)" },
  { key: "HALAL", label: "Halal certified? (y/n)" },
  { key: "ORGANIC_CERT", label: "Organic certified? (y/n)" },
  { key: "EU_CERTIFIED", label: "European Union certified? (y/n)" },
  { key: "VEGETARIAN", label: "Is this item vegetarian? (y/n)" },
  { key: "BIOENGINEERED_FOOD", label: "Is this item a “bioengineered food,” as defined in 7 CFR 66.1 (contains genetic material modified through rDNA techniques, modification could not otherwise be obtained through conventional breeding found in nature)?" },
  { key: "DIS_BIOENGINEER_FOOD", label: "Is this item exempt from disclosure requirements for bioengineered foods, as allowed for by 7 CFR 66?" },
  { key: "DNA_CRISPR", label: "Contains gene edited DNA (CRISPR)? (y/n)" },
  { key: "DNA_CRISPR_REFINED", label: "Made from gene edited (CRISPR) material, not detectable, highly refined ingredient?  (y/n)" },
  { key: "PROP_65 --- roll up", label: "Is this item Prop 65 certified? (y/n)" },
  { key: "SENS_GLUTEN_FR_CERT", label: "Do you have Gluten Free Certification (y/n)?" },
  { key: "KOSHER_EXPIRE", label: "Kosher certification expiration date" },
  { key: "HALAL_CERT_EXPIRE", label: "Indicate the expiration date of the Halal certificate" },
  { key: "ORGANIC_CERT_EXPIRE", label: "Indicate the expiration date of the Organicl certificate" },
  { key: "go live 1/18/24", label: "If ORGANIC_CERT = YES then Attachment type Packaging Label is Requried" },
  { key: "C_SUPPLRADDTIVE_LIST", label: "If this item contains incidental additives or processing aids, please identify them" },
  { key: "SENS_SRC_COLOR_ART", label: "If natural or artificial color(s) are added, identify the sourceKD - follow up" },
  { key: "KOSHER_TYPE", label: "If item is Kosher, select the type of Kosher certification" },
  { key: "HALAL_QUALIFIES", label: "Can item be Halal certified? (y/n)" },
  { key: "EXP_BIOENGINEER_FOOD", label: "Under what exemption does this item apply?" },
  { key: "Specification Code_system_populate", label: "Specification Code" },
  { key: "Description_system_populate", label: "Description" },
  { key: "Version_system_populate", label: "Version" },
  { key: "Class_system_populate", label: "Class" },
  { key: "RM_Category-37c87f8afd30", label: "Raw Material Category" },
  { key: "Schreiber Item Number_system_populate", label: "Schreiber Item Number" },
  { key: "MANUFACTURE_NAME", label: "Identifies the manufacturer name if supplied by a Broker" },
  { key: "FCC", label: "Is this item FCC / Codex compliant? (y/n)" },
  { key: "NATURAL_FLAV_SOURCE", label: "If natural flavor what is the source - free text" },
  { key: "ENZYME_ANIMAL_TYPE", label: "If Enzyme source is animal, identify type of animal" },
  { key: "STARCH_E_NUMBER", label: "If corn starch, what is the E Number" },
  { key: "TYPES_OF_CULTURES", label: "If cultures are present, select the culture type(s)" },
  { key: "HAZARDOUS_CLASS", label: "If hazardous material, what is the class" },
  { key: "FLASH_POINT", label: "What is the flash point?" },
  { key: "BOILING_POINT", label: "What is the boiling point?" },
  { key: "IRRADIATED", label: "Is the material irradiated? (y/n)" },
  { key: "FS_HAZARD", label: "Describe the hazard(s) that need to be addressed" },
  { key: "DAIRY_SOLIDS", label: "Does this raw material contain Dairy Solids?" },
  { key: "FORMULA_GRADE", label: "If this material contains dairy solids, what is the grade of the dairy solids?" },
  { key: "C_INTENDEDUSEMFG", label: "MFG Intended Use:" },
  { key: "C_MELT", label: "Melt" },
  { key: "FOREIGN_DAIRY", label: "Does your product contain any Non-US Dairy" },
  { key: "RM_HS_CODE", label: "If this product contains Non-Us dairy, what is the 6 digit HS code (Harmonized System Code)" },
  { key: "HACCP_PROGRAM", label: "Do you have an established and functional HACCP program in place at your manufacturing plant for this item? (y/n)" },
  { key: "KEEPING_QUALITY_PGRM", label: "Do you have a keeping quality or retention program? (y/n)" },
  { key: "QA_TEST", label: "Is in-process quality testing being done? (y/n)" },
  { key: "QA_TEST_FREQUENCY", label: "What is the frequency of in-process quality testing?" },
  { key: "DENSITY", label: "Density (Kg Per Lt) - Primary UOM Conversion" },
  { key: "DEXTROSE_EQUIVALENT", label: "Measure of sweetness level.  Test range: 0-100" },
  { key: "PYROPHOSPHATE", label: "Pyrophosphate content" },
  { key: "REFRACTIVE_INDEX", label: "Measure of refractive index" },
  { key: "SCORCHED_PARTICLES", label: "Measurement of scorched particles" },
  { key: "INSOLUBLE_SUBST", label: "Insoluble substance is the amount of substance that does not dissolve in a solvent." },
  { key: "SOLUBILITY", label: "Solubility" },
  { key: "VISCOSITY_BROOK_TYPE", label: "NEW - Type of Brookfield" },
  { key: "VISCOSITY_SPINDEL_NU", label: "Spindle Number" },
  { key: "VISCOSITY_RPM_SPEED", label: "RPM speed" },
  { key: "PALLET_HOOD_MATRL", label: "Identifies the pallet hood material such as cardboard" },
  { key: "C_CULTURE_G_WEIGHT", label: "Culture Weight (g) -  1 packet" },
  { key: "ALLERGEN_CRUSTCA_LVL", label: "Crustacean shellfish amount/100g" },
  { key: "ALLERGEN_CRUSTCA_SRC", label: "Crustacean shellfish - source of" },
  { key: "ALLERGEN_EGG_LVL", label: "Egg products or egg derivatives amount/100g" },
  { key: "ALLERGEN_EGG_SRC", label: "Egg products or egg derivatives - source of" },
  { key: "ALLERGEN_FISH_LVL", label: "Fish amount/100g" },
  { key: "ALLERGEN_FISH_SRC", label: "Fish - source of" },
  { key: "ALLERGEN_DAIRY_LVL", label: "Dairy products or dairy derivatives amount/100g" },
  { key: "ALLERGEN_DAIRY_SRC", label: "Dairy products or dairy derivatives - source of" },
  { key: "ALLERGEN_PEANUTS_LVL", label: "Peanut amount/100g" },
  { key: "ALLERGEN_PEANUTS_SRC", label: "Peanut - source of" },
  { key: "ALLERGEN_SESAME_LVL", label: "Sesame seeds amount/100g?" },
  { key: "ALLERGEN_SOYPROD_LVL", label: "Soy products & hydrolysates amount/100g" },
  { key: "ALLERGEN_SOYPROD_SRC", label: "Soy products & hydrolysates - source of" },
  { key: "ALLERGEN_SOY_CCNUT", label: "If soybean or coconut oil is present, is soybean oil and/or coconut oil NOT highly refined? (refined, bleached and deodorized)" },
  { key: "ALLERGEN_TREENUT_LVL", label: "Treenut or nut derivatives (includes coconut and/or coconut oil) amount/100g" },
  { key: "ALLERGEN_TREENUT_SRC", label: "Treenut - source of" },
  { key: "ALLERGEN_WHEAT_LVL", label: "Wheat products and hydrolysates amount/100g" },
  { key: "ALLERGEN_WHEAT_SRC", label: "Wheat Products And Hydrolysates - source of" },
  { key: "CARAMEL_COLOR_CLASS", label: "If caramel color is present, identity the class" },
  { key: "CARAMEL_METH_LVL", label: "If class III or IV, indicate the level of 4-Methylimidazole" },
  { key: "SENS_GLUTEN_LVL", label: "Gluten  (from wheat, spelt, kamut, triticale, oats, rye and / or barley) level" },
  { key: "SENS_SRC_SEED", label: "If seeds or seed derivatives present, identify the source" },
  { key: "SENS_SRC_HERB", label: "If herb or spices are present, identity the source" },
  { key: "SENS_PALM_SUSTAINABL", label: "Does palm oil/derivative come form a sustainable source?" },
  { key: "SENS_PALM_SUS_SOURCE", label: "If Yes, what RSPO supply chain method(s) is used." },
  { key: "SENS_PALM_SUS_OPTION", label: "If No, is a sustainable sourcing option availabel?" },
  { key: "SOURCE_SULFITE", label: "If Sulfites, sulfur dioxide, sodium (bi)-sulfate are present, what is the source?" },
  { key: "SENS_SULFITE_LVL", label: "If sulfites, sulfur dioxide, sodium (bi)-sulfate are present, what is the level?" },
  { key: "ASH", label: "Ash content" },
  { key: "CASEIN", label: "Casein content" },
  { key: "FAT_MILK", label: "Milkfat content" },
  { key: "FDM", label: "Fat in dry matter" },
  { key: "LACTOSE", label: "Lactose content" },
  { key: "MELTING_POINT", label: "Melting point" },
  { key: "MELT_TEMP_F", label: "Melt temperature °C" },
  { key: "MELT_TEMP_C", label: "Melt temperature" },
  { key: "METALS_HEAVY", label: "Heavy metals content" },
  { key: "LEAD", label: "Measure of the lead content" },
  { key: "NORBIXIN", label: "Norbixin - color concentration" },
  { key: "NPN", label: "Non protein nitrogen content" },
  { key: "PEROXIDE", label: "Peroxide value - a measure of rancidity" },
  { key: "AFLATOXIN", label: "Aflatoxin - measure of the toxic chemical metabolites produced by Aspergillus molds" },
  { key: "LOSS_ON_IGNT", label: "The mass loss after heating to a specific temperature allowing volatile substances to escape" },
  { key: "RESIDUE_ON_IGNT", label: "Measures the amount of residual substance not volatilized" },
  { key: "PROTEASE_ACTIVITY", label: "Protease activity - measure of protein breakdown" },
  { key: "ENZYME_ACTIVITY", label: "Measure of the activity of an enzyme" },
  { key: "PURITY", label: "Purity - assay, percent pure" },
  { key: "SOLIDS_MILK_NONFAT", label: "Milk solids nonfat (MSNF) content" },
  { key: "SOLIDS_MILK", label: "Milk Solids" },
  { key: "STABILIZER_AMOUNT", label: "Stabilizer content" },
  { key: "SORBIC_ACID", label: "Sorbic acid content" },
  { key: "TITRATABLE_ACIDITY", label: "Measure of titratable acidity" },
  { key: "WHEY_PROTEIN", label: "Whey protein content" },
  { key: "WPN", label: "Whey protein nitrogen content" },
  { key: "C_SUPPLIER_MIRCO_COM", label: "If no, please state your specificaitons" },
  { key: "MICRO_LISTERIA", label: "Listeria present? (positive / negative)" },
  { key: "MICRO_SALMONELLA", label: "Salmonella present? (positive / negative)" },
  { key: "MICRO_STPH_AUREUS", label: "Indicates the maximum acceptable level of Staphylococcus aureus" },
  { key: "MICRO_YEAST", label: "Indicates the maximum acceptable level of yeast" },
  { key: "MICRO_MOLD", label: "Identifies the maximum acceptable level of mold" },
  { key: "MICRO_ENTEROTOXIN", label: "Enterotoxin present? (yes/no)" },
  { key: "MICRO_PLATE_C", label: "Indicates the maximum acceptable level of standard plate count" },
  { key: "MICRO_COLIFORM", label: "Identifies the maximum acceptable level of coliform" },
  { key: "MICRO_HLB", label: "Identifies the maximum acceptable level of heterofermentative Lactobacilli" },
  { key: "HETEROTROPHS", label: "Measure of Heterotrophic bacteria" },
  { key: "COLOR_NCI", label: "NCI color score range. Applies to cheese and plain CC formulas." },
  { key: "HUNTER_L_COLOR", label: "Hunter L - measure of the color lightness or darkness" },
  { key: "HUNTER_A_COLOR", label: "Hunter A - measure of the color greeness or redness" },
  { key: "HUNTER_B_COLOR", label: "Hunter B - measure of the color blueness or yellowness" },
  { key: "KOSHER_QUALIFIES", label: "Can item be Kosher certified? (y/n)" },
  { key: "ORGANIC_PCT_LEVEL", label: "Percent of the product which is certified organic. If the product doesn’t contain Organic, the % will be 0." },
  { key: "ORGANIC_CERT_AGENCY", label: "Organic certification agency name" },
  { key: "RBST_FREE", label: "Is this item rBST free? (y/n)" },
  { key: "VEGETARIAN_TYPE", label: "If the item is classified as vegetarian, select the vegetarian type." },
  { key: "GMO - follow - REMOVE QUESTION", label: "Contains or made from genetically modified organisms? (y/n)" },
  { key: "PROP_65_CHEMICAL", label: "If yes, what is the chemical" },
  { key: "TRIGGER_PRO_65", label: "Based on intended standard usage levels in our finished products – would it trigger prop 65 warning? (y/n)" },
];


/** 👉  NEW: build starter sheet once, reuse everywhere */
export const QUESTIONS_CSV = [
  'ID,Question,Answer',                                     // header row
  ...QUESTIONS.map((q) => `${q.key},"${q.label.replace(/"/g, '""')}",`)
].join('\n');