/**
 * 
 * Template for sheet questions with key, label and source tracking
 */
export interface Question {
  key: string;
  label: string;
  answer: string;
  source: 'LLM' | 'user' | 'PDF' | '';
}

/**
 * Static list of questions extracted from the JSON
 */
export const QUESTIONS: Question[] = [
  { key: "C_SUPPLIERLEGALLABEL", label: "Legal Label Description", answer: "A strawberry light fruit prep for yogurt applications", source: "PDF" },
  { key: "C_SUPPLIERINGRSTMT", label: "Ingredient Statement", answer: "Water, Strawberries, Crystalline Fructose, Modified Food Starch, Fruit and Vegetable Juice for Color, Natural Flavor, Malic Acid, Sucralose, Potassium Sorbate as a Preservative.", source: "PDF" },
  { key: "C_SUPPIERITEMNMBR", label: "Supplier Item Number", answer: "503941-04", source: "PDF" },
  { key: "C_FLAVORDESC", label: "Flavor Description", answer: "Strawberry", source: "PDF" },
  { key: "C_AROMA", label: "Aroma", answer: "", source: "PDF" },
  { key: "C_APPEARANCE", label: "Appearance", answer: "", source: "PDF" },
  { key: "C_COLOR_NCISENSORYTXT", label: "Color", answer: "Red", source: "PDF" },
  { key: "C_PHY_BODY_TEXTURE", label: "Body and Texture", answer: "Viscous liquid", source: "PDF" },
  // { key: "BROKER", label: "Are you a Broker Y/N", answer: "No", source: "PDF" },
  // { key: "PACKED_COUNTRY_OR", label: "Identifies the country where the item is packed or produced", answer: "United States", source: "PDF" },
  // { key: "FLAVOR_SOURCE Target-12d455b46949", label: "If flavors are used, select the flavor source (natural, artificial or natural and artificial)", answer: "Natural With Other Natural Flavor", source: "PDF" },
  // { key: "ENZYME_SOURCE", label: "If enzymes are used, select the enzyme source (microbiological, animal or plant)", answer: "Not Applicable", source: "PDF" },
  // { key: "STARCH_SOURCE", label: "If starch(es) are used, select the source of starch(es)", answer: "Corn", source: "PDF" },
  // { key: "HAZARDOUS_MTL", label: "Is the raw material considered hazardous and need special handling? (y/n)", answer: "No", source: "PDF" },
  // { key: "READY_TO_EAT", label: "This item is ready to eat? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "MICRO_RED_TREAT", label: "Identify the treatment used to reduce the microbial load of this product", answer: "Pasteurization", source: "PDF" },
  // { key: "FS_ADD_PROCESSING", label: "Does this item need additional processing to address chemical or physical hazards? (y/n)", answer: "No", source: "PDF" },
  // { key: "C_RECYLINGINSTR", label: "Recycling Instructions", answer: "", source: "PDF" },
  // { key: "C_STORAGEINSTR", label: "Storage Instructions", answer: "Store 40°F and below", source: "PDF" },
  // { key: "C_PKGMARKINGS", label: "Marking on Package and/ Container", answer: "Kosher Symbol, Production Date, Use by Date, Storage Requirements, and Company Address", source: "PDF" },
  // { key: "C_PKGWARNINGCAUTION", label: "Caution/Warning on Packag and/or Container", answer: "", source: "PDF" },
  // { key: "C_CODE_EXPLANATION", label: "Code Explanation", answer: "PRODUCTION BATCH NUMBER PLUS DATE OF MANUFACTURE", source: "PDF" },
  // { key: "Item Line (%min and % max, COO, and Function)", label: "Range Formula", answer: "WATER - FOR FRUIT PREP (45-55%, United States, MOISTURE) STRAWBERRIES (25-35%, United States,Morocco, FRUIT) FRUCTOSE (5-15%, Turkey, SWEETENER) MODIFIED FOOD STARCH (5-15%, United States, STABILIZER) FRUIT AND VEGETABLE JUICE (COLOR) (1-10%, United States, COLOR) NATURAL FLAVOR (0.01-1%, United States, FLAVOR) MALIC ACID (0.01-1%, Canada, ACIDULANT [SYNTHETICALLY DERIVED) SUCRALOSE (0.01-1%, China, SWEETENER) POTASSIUM SORBATE (INCIDENTAL) (0.01-1%, China, PRESERVATIVE)", source: "PDF" },
  // { key: "Form/Extracted From , and Additive Number, and Size or Concentration Rate", label: "Range Formula", answer: "", source: "PDF" },
  // { key: "RM_DAIRY", label: "NEW - Does your product contain any dairy? y/n", answer: "No", source: "PDF" },
  // { key: "C_SUPPLIERADDITIVE", label: "Does this item contain any incidental additives or processing aids", answer: "0", source: "PDF" },
  // { key: "C_SUPPLR_ADDTVCNTRL", label: "Are controls in place such that there would be no other unlabeled additives in this item, besides those indicated?", answer: "1", source: "PDF" },
  // { key: "SHIP_TEMP_RANGE", label: "Identifies the range of temperature within which an item should be shipped", answer: "40", source: "PDF" },
  // { key: "STORAGE_TEMP_RANGE", label: "Identifies the range of temperature within which an item should be stored", answer: "40", source: "PDF" },
  // { key: "SHELF_LIFE - MAPPED to GUARANTEE", label: "Identifies the expected shelf life - unopened", answer: "", source: "PDF" },
  // { key: "SHELFLIFE_OPEN", label: "Shelf life of product after package has been opened", answer: "14", source: "PDF" },
  // { key: "LEAD_TIME", label: "Lead time in days", answer: "7", source: "PDF" },
  // { key: "MIN_ORDER_QTY", label: "Minimum order quantity in pounds", answer: "2000", source: "PDF" },
  // { key: "DENSITY_2", label: "Density (Lb/Gal_Us)", answer: "8.902", source: "PDF" },
  // { key: "SCOVILLE_UNITS", label: "Scoville units - measurement of flavor heat level", answer: "", source: "PDF" },
  // { key: "PARTICLE_SZ_ON", label: "The amount of particles retained on a specific mesh size", answer: "", source: "PDF" },
  // { key: "PARTICLE_SZ_THRU", label: "The amount of particles that passed thru a specific mesh size", answer: "", source: "PDF" },
  // { key: "SIEVE_SIZE_ON", label: "Sieve size used to measure the particle size retained on the mesh", answer: "", source: "PDF" },
  // { key: "SIEVE_SIZE_THRU", label: "Sieve size used to measure the particle size passed thru the mesh", answer: "", source: "PDF" },
  // { key: "PIECE_SIZE", label: "Particulate size in inches", answer: "", source: "PDF" },
  // { key: "PIECE_RETENTION", label: "Amount (%) of particles retained after rinsing with water (wet weight basis)", answer: "", source: "PDF" },
  // { key: "SPECIFIC_GRAVITY", label: "Specific gravity", answer: "", source: "PDF" },
  // { key: "SUGAR_BRIX", label: "Brix - measurement of sugar level", answer: "17", source: "PDF" },
  // { key: "VISCOSITY1", label: "Viscosity", answer: "5", source: "PDF" },
  // { key: "VISCOSITY_METHOD", label: "NEW QUESTION - Viscosity method", answer: "Bostwick (cenco) (cm)", source: "PDF" },
  // { key: "VISCOSITY_TIME", label: "NEW QUESTION - Viscosity Time in seconds", answer: "30", source: "PDF" },
  // { key: "VISCOSITY_TEMP", label: "NEW QUESTION - Viscosity Temp F", answer: "40", source: "PDF" },
  // { key: "PKG_CONTAINER_TYPE", label: "Describes the package type", answer: "Bag in Box", source: "PDF" },
  // { key: "PACKAGING_MATERIAL", label: "Identifies the make up of the packaging material", answer: "Cardboard", source: "PDF" },
  // { key: "PALLET_HOOD", label: "Is the item palletized with a pallet hood? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "PALLET_SHRINK_WRAP", label: "Is the item palletized with shrink wrap? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "PALLET_SLIP_SHEET", label: "Is the item palletized with a slip sheet? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SHIP_CTNR_GROSS_WGT", label: "Total gross weight of the ship container (including product and packaging materials)", answer: "43", source: "PDF" },
  // { key: "SHIP_CTNR_NET_WEIGHT", label: "Net weight of product in a ship container (not including any packaging materials)", answer: "40", source: "PDF" },
  // { key: "SHIP_CTNR_PER_LAYER", label: "Number of ship containers per pallet layer", answer: "10", source: "PDF" },
  // { key: "SHIP_CTNR_PER_PALLET", label: "Number of ship containers per pallet", answer: "40", source: "PDF" },
  // { key: "SHIP_CTNR_LENGTH", label: "Length target of a ship container", answer: "52", source: "PDF" },
  // { key: "SHIP_CTNR_WIDTH", label: "Width target of a ship container", answer: "52", source: "PDF" },
  // { key: "SHIP_CTNR_HEIGHT", label: "Height target of a ship container", answer: "60", source: "PDF" },
  // { key: "ALLERGEN_CRUSTACEA", label: "Allergen crustacean / shellfish present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_CRUSTC_PISL", label: "Crustacean shellfish present in any item manufactured on same line", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_CRUSTCA_PIF", label: "Crustacean shellfish present in same manufacturing facility", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_EGG", label: "Allergen egg present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_EGG_PISL", label: "Egg products or egg present in any item manufactured on the same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_EGG_PIF", label: "Egg products or egg derivatives present in same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_FISH", label: "Allergen fish present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_FISH_PISL", label: "Fish present in any item manufactured on the same line", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_FISH_PIF", label: "Fish present in same manufacturing facility", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_DAIRY", label: "Allergen dairy present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_DAIRY_PISL", label: "Dairy products or dairy derivatives present in any item manufactured on the same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_DAIRY_PIF", label: "Dairy products or dairy derivatives present in same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_PEANUTS", label: "Allergen peanuts present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_PEANUT_PISL", label: "Peanuts present in any item manufactured on the same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_PEANUTS_PIF", label: "Peanuts present in same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_SESAME", label: "Allergen sesame seeds or derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_SESAME_PIF", label: "Sesame seeds or derivatives present in same manufacturing facility? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_SESAME_PISL", label: "Sesame seeds or derivatives present in any item manufactured on the same line? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_SOYBEANS", label: "Allergen soybean present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_SOYPRO_PISL", label: "Soy products & hydrolysates present in any item manufactured on same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_SOYPROD_PIF", label: "Soy products & hydrolysates present in same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_TREENUT", label: "Allergen treenut present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_TREENU_PISL", label: "Treenut or treenut derivatives (includes coconut) present in any item manufactured on the same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_TREENUT_PIF", label: "Treenut or nut derivatives (includes coconut and/or coconut oil) present in the same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_WHEAT", label: "Allergen wheat present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ALLERGEN_WHEAT_PISL", label: "Wheat products and hydrolysates present in any item manufactured on same line", answer: "Yes", source: "PDF" },
  // { key: "ALLERGEN_WHEAT_PIF", label: "Wheat products and hydrolysates present in same manufacturing facility", answer: "Yes", source: "PDF" },
  // { key: "SENS_APPLE", label: "Apple present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_COLOR_ART", label: "Artificial color present (certificated colors)? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_COLORS_NATURAL", label: "Natural color present? No certificated colors (i.e. annatto, beet juice, turmeric) (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SENS_SWEETNER_ART", label: "Artificial sweetener present? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SENS_BEEF", label: "Beef or beef derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_BEET_SUGAR", label: "Beet sugar present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_CELERY", label: "Celery present – roots, leaves, stalks, seeds? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_CHOCOLATE", label: "Chocolate and / or chocolate derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_CORN", label: "Corn or corn derivatives present? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SENS_GARLIC", label: "Garlic or garlic derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_GLUTEN", label: "Gluten (from wheat, spelt, kamut, tritcale, oats, rye and / or barley) present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_GLUTEN_PIF", label: "Gluten present in same manufacturing facility?", answer: "Yes", source: "PDF" },
  // { key: "SENS_GLUTEN_PISL", label: "Gluten present in any item manufactured on same line?", answer: "Yes", source: "PDF" },
  // { key: "SENS_GLUTEN_HYDROLY", label: "Do any ingredients used to make this product (including growth media and substrates) contain gluten?", answer: "No", source: "PDF" },
  // { key: "SENS_GLUTEN_DISTILLE", label: "If gluten was present as an ingredient, was distillation used to remove any residual protein?", answer: "No", source: "PDF" },
  // { key: "SENS_MSG", label: "Monosodium glutamate added? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_SYN_BIO", label: "Are synthetically modified organisms intentionally added? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_PRESERVATIVES", label: "Preservatives or antioxidants present? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SENS_PRSRV_INCID", label: "Are incidental preservatives or antioxidants present? Y/N (These additives may be present from cross contact or be ingredients within ingredients etc. but have no technical or functional effect).", answer: "No", source: "PDF" },
  // { key: "SENS_PORK", label: "Pork derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_SEEDS", label: "Seed or seed derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_MUSHROOM", label: "Are mushrooms present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_TBHQ", label: "Is TBHQ (used as a preservative for vegetable oils and edible animal fats) present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_YEAST_DERIV", label: "Yeast and / or yeast derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_HERB_SPICE", label: "Are herb or spices present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_LUPINE", label: "Lupine or lupine derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_PART_HYDR_OIL", label: "Any partially hydrogenated oils present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_RENNET", label: "Rennet present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_NANO", label: "Nanotech Materials Intentionally added or made approx. size 1-100nm? (y/n)", answer: "No", source: "PDF" },
  // { key: "POTASSIUM_SORBATE_FR", label: "Potassium sorbate present? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "SENS_BUCKWHEAT", label: "Buckwheat or buckwheat derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_MUSTARD", label: "Mustard or mustard derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_BEE_POLLEN", label: "Bee Pollen/Propolis present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_ROYAL_JELLY", label: "Royal Jelly present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_MANGO", label: "Mango present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_PEACH", label: "Peach present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_TOMATO", label: "Tomato present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_LATEX", label: "Latex (natural rubber) present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_ORANGE", label: "Oranges present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_KIWI_FRUIT", label: "Kiwi Fruit present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SNES_CHICKEN", label: "Chicken present? (y/n) --- Poultry or poultry derivatives present? (y/n)", answer: "", source: "PDF" },
  // { key: "SENS_BANANA", label: "Banana present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_YAMS", label: "Yams present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_GELATIN", label: "Gelatin present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_PALM_OIL", label: "Palm oil or Palm oil derivatives present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ADTV_BHA", label: "BHA (butylated hydroxyanisole) present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ADTV_BHT", label: "BHT (butylated hydroxytoluene) present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ADTV_TOCOPHEROL_NAT", label: "Natural tocopherol present? (y/n)", answer: "No", source: "PDF" },
  // { key: "ADTV_TOCOPHEROL_SYNT", label: "Synthetic tocopherol present? (y/n)", answer: "No", source: "PDF" },
  // { key: "SENS_SULFITE", label: "Sulfites, sulfur dioxide, sodium (bi)-sulfate present? (y/n)", answer: "No", source: "PDF" },
  // { key: "CALORIES", label: "Calories per 100g - no rounding", answer: "74.577", source: "PDF" },
  // { key: "FATS", label: "Total fat value per 100g - no rounding", answer: "0.077", source: "PDF" },
  // { key: "FATS_SAT", label: "Saturated fat value per 100g - no rounding", answer: "0.015", source: "PDF" },
  // { key: "FATS_TRANS", label: "Trans fat value per 100g - no rounding", answer: "0.001", source: "PDF" },
  // { key: "FATS_POLYUNSAT", label: "Polyunsaturated fat value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "FATS_MONOUNSAT", label: "Monounsaturated fat value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "CHOLESTEROL", label: "Cholesterol value per 100g - no rounding", answer: "0", source: "PDF" },
  // { key: "SODIUM", label: "Sodium value per 100g - no rounding", answer: "14.978", source: "PDF" },
  // { key: "CARBOHYDRATES", label: "Total carbohydrates value per 100g - no rounding", answer: "17.838", source: "PDF" },
  // { key: "FIBER_NEW", label: "NEW - Dietary fiber (basis new definition) value per 100g – no rounding", answer: "0.64", source: "PDF" },
  // { key: "FIBER_SOLUBLE", label: "Soluble fiber value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "FIBER_INSOLUBLE", label: "Insoluble fiber value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "SUGARS", label: "Sugars value per 100g - no rounding", answer: "11.346", source: "PDF" },
  // { key: "SUGAR_ADD", label: "NEW - Added Sugars value per 100g", answer: "9.873", source: "PDF" },
  // { key: "SUGAR_ALCOHOL", label: "Sugar alcohol per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "CARBOHYDRATES_OTHER", label: "Other carbohydrate value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "PROTEIN", label: "Protein value per 100g - no rounding", answer: "0.211", source: "PDF" },
  // { key: "VIT_D_MCG", label: "NEW - Vitamin D value per 100g (mcg) - no rounding", answer: "0", source: "PDF" },
  // { key: "CALCIUM", label: "Calcium value per 100g - no rounding", answer: "6.185", source: "PDF" },
  // { key: "IRON", label: "Iron value per 100g - no rounding", answer: "0.257", source: "PDF" },
  // { key: "POTASSIUM", label: "Potassium value per 100g - no rounding", answer: "70.584", source: "PDF" },
  // { key: "VIT_A_MCG", label: "NEW - Vitamin A value retinol activity equivalents per 100g - no rounding", answer: "0.675", source: "PDF" },
  // { key: "VIT_C", label: "Vitamin C value per 100g - no rounding", answer: "12.36", source: "PDF" },
  // { key: "VIT_E", label: "Vitamin E value per 100g - no rounding", answer: "", source: "PDF" },
  // { key: "VIT_E_MG", label: "NEW - Vitamin E value per 100g (mg) - no rounding", answer: "0.13", source: "PDF" },
  // { key: "THIAMIN", label: "Thiamin value per 100g - no rounding", answer: "0.007", source: "PDF" },
  // { key: "RIBOFLAVIN", label: "Riboflavin (vitamin B2) value per 100g - no rounding", answer: "0.015", source: "PDF" },
  // { key: "NIACIN", label: "Niacin value per 100g - no rounding", answer: "0.177", source: "PDF" },
  // { key: "VIT_B6", label: "Vitamin B6 (pyridoxine) value per 100g - no rounding", answer: "0.008", source: "PDF" },
  // { key: "FOLIC_ACID_NEW", label: "NEW - Folate DFE (folate, folic acid) value per 100g – no rounding", answer: "5.1", source: "PDF" },
  // { key: "VIT_B12", label: "Vitamin B12 value per 100g - no rounding", answer: "0", source: "PDF" },
  // { key: "BIOTIN", label: "Biotin value per 100g - no rounding", answer: "0.33", source: "PDF" },
  // { key: "PANTOTHENIC_ACID", label: "Pantothenic acid value per 100g - no rounding", answer: "0.032", source: "PDF" },
  // { key: "PHOSPHORUS", label: "Phosphorus value per 100g - no rounding", answer: "3.9", source: "PDF" },
  // { key: "IODINE", label: "Iodine value per 100g - no rounding", answer: "0", source: "PDF" },
  // { key: "MAGNESIUM", label: "Magnesium value per 100g - no rounding", answer: "3.319", source: "PDF" },
  // { key: "ZN", label: "Zinc value per 100g - no rounding", answer: "0.039", source: "PDF" },
  // { key: "COPPER", label: "Copper value per 100g - no rounding", answer: "0.024", source: "PDF" },
  // { key: "MANGANESE", label: "Manganese value per 100g - no rounding", answer: "0.088", source: "PDF" },
  // { key: "MOISTURE", label: "Moisture content", answer: "80.872", source: "PDF" },
  // { key: "NATAMYCIN", label: "Natamycin", answer: "", source: "PDF" },
  // { key: "PH", label: "pH - measure of acidity or basicity", answer: "3.3", source: "PDF" },
  // { key: "SALT", label: "Salt content", answer: "", source: "PDF" },
  // { key: "SOLIDS", label: "Total solids content", answer: "19.128", source: "PDF" },
  // { key: "SOLIDS_CORN_SYRUP", label: "Corn syrup solids content", answer: "0", source: "PDF" },
  // { key: "SOLIDS_H_FRUCTOSE_CS", label: "High fructose corn syrup solids content", answer: "0", source: "PDF" },
  // { key: "SUCROSE", label: "Sucrose content", answer: "0", source: "PDF" },
  // { key: "SUCROSE_EQUIVALENT", label: "Sucrose equivalent content", answer: "0", source: "PDF" },
  // { key: "RM_MICRO_REQ", label: "Can you meet Microbiological specifications - y/n", answer: "Yes", source: "PDF" },
  // { key: "KOSHER_CERT", label: "Kosher certification? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "HALAL", label: "Halal certified? (y/n)", answer: "No", source: "PDF" },
  // { key: "ORGANIC_CERT", label: "Organic certified? (y/n)", answer: "No", source: "PDF" },
  // { key: "EU_CERTIFIED", label: "European Union certified? (y/n)", answer: "No", source: "PDF" },
  // { key: "VEGETARIAN", label: "Is this item vegetarian? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "BIOENGINEERED_FOOD", label: "Is this item a “bioengineered food,” as defined in 7 CFR 66.1 (contains genetic material modified through rDNA techniques, modification could not otherwise be obtained through conventional breeding found in nature)?", answer: "No", source: "PDF" },
  // { key: "DIS_BIOENGINEER_FOOD", label: "Is this item exempt from disclosure requirements for bioengineered foods, as allowed for by 7 CFR 66?", answer: "Yes", source: "PDF" },
  // { key: "DNA_CRISPR", label: "Contains gene edited DNA (CRISPR)? (y/n)", answer: "No", source: "PDF" },
  // { key: "DNA_CRISPR_REFINED", label: "Made from gene edited (CRISPR) material, not detectable, highly refined ingredient? (y/n)", answer: "No", source: "PDF" },
  // { key: "PROP_65 --- roll up", label: "Is this item Prop 65 certified? (y/n)", answer: "", source: "PDF" },
  // { key: "SENS_GLUTEN_FR_CERT", label: "Do you have Gluten Free Certification (y/n)?", answer: "No", source: "PDF" },
  // { key: "KOSHER_EXPIRE", label: "Kosher certification expiration date", answer: "2025-08-31", source: "PDF" },
  // { key: "HALAL_CERT_EXPIRE", label: "Indicate the expiration date of the Halal certificate", answer: "", source: "PDF" },
  // { key: "ORGANIC_CERT_EXPIRE", label: "Indicate the expiration date of the Organicl certificate", answer: "", source: "PDF" },
  // { key: "go live 1/18/24", label: "If ORGANIC_CERT = YES then Attachment type Packaging Label is Requried", answer: "", source: "PDF" },
  // { key: "C_SUPPLRADDTIVE_LIST", label: "If this item contains incidental additives or processing aids, please identify them", answer: "", source: "PDF" },
  // { key: "SENS_SRC_COLOR_ART", label: "If natural or artificial color(s) are added, identify the source KD - follow up", answer: "Carrot Juice;Pumpkin;Sweet Potato", source: "PDF" },
  // { key: "KOSHER_TYPE", label: "If item is Kosher, select the type of Kosher certification", answer: "KOSHER PARVE", source: "PDF" },
  // { key: "HALAL_QUALIFIES", label: "Can item be Halal certified? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "EXP_BIOENGINEER_FOOD", label: "Under what exemption does this item apply?", answer: "Refined: derived from BE crop, but does not contain detectable modified DNA", source: "PDF" },
  // { key: "Specification Code_system_populate", label: "Specification Code", answer: "", source: "PDF" },
  // { key: "Description_system_populate", label: "Description", answer: "", source: "PDF" },
  // { key: "Version_system_populate", label: "Version", answer: "", source: "PDF" },
  // { key: "Class_system_populate", label: "Class", answer: "", source: "PDF" },
  // { key: "RM_CATEGORY RM_Category-37c87f8afd30", label: "Raw Material Category", answer: "Fruit - Sauce, Pulp, Puree, Composite", source: "PDF" },
  // { key: "Schreiber Item Number_system_populate", label: "Schreiber Item Number", answer: "", source: "PDF" },
  // { key: "MANUFACTURE_NAME", label: "Identifies the manufacturer name if supplied by a Broker", answer: "", source: "PDF" },
  // { key: "FCC", label: "Is this item FCC / Codex compliant? (y/n)", answer: "", source: "PDF" },
  // { key: "NATURAL_FLAV_SOURCE", label: "If natural flavor what is the source - free text", answer: "Derived from strawberry with other natural flavors", source: "PDF" },
  // { key: "ENZYME_ANIMAL_TYPE", label: "If Enzyme source is animal, identify type of animal", answer: "", source: "PDF" },
  // { key: "STARCH_E_NUMBER", label: "If corn starch, what is the E Number", answer: "E1442", source: "PDF" },
  // { key: "TYPES_OF_CULTURES", label: "If cultures are present, select the culture type(s)", answer: "", source: "PDF" },
  // { key: "HAZARDOUS_CLASS", label: "If hazardous material, what is the class", answer: "", source: "PDF" },
  // { key: "FLASH_POINT", label: "What is the flash point?", answer: "", source: "PDF" },
  // { key: "BOILING_POINT", label: "What is the boiling point?", answer: "", source: "PDF" },
  // { key: "IRRADIATED", label: "Is the material irradiated? (y/n)", answer: "", source: "PDF" },
  // { key: "FS_HAZARD", label: "Describe the hazard(s) that need to be addressed", answer: "", source: "PDF" },
  // { key: "DAIRY_SOLIDS", label: "Does this raw material contain Dairy Solids?", answer: "No", source: "PDF" },
  // { key: "FORMULA_GRADE", label: "If this material contains dairy solids, what is the grade of the dairy solids?", answer: "", source: "PDF" },
  // { key: "C_INTENDEDUSEMFG", label: "MFG Intended Use:", answer: "", source: "PDF" },
  // { key: "C_MELT", label: "Melt", answer: "", source: "PDF" },
  // { key: "FOREIGN_DAIRY", label: "Does your product contain any Non-US Dairy", answer: "No", source: "PDF" },
  // { key: "RM_HS_CODE", label: "If this product contains Non-Us dairy, what is the 6 digit HS code (Harmonized System Code)", answer: "", source: "PDF" },
  // { key: "HACCP_PROGRAM", label: "Do you have an established and functional HACCP program in place at your manufacturing plant for this item? (y/n)", answer: "", source: "PDF" },
  // { key: "KEEPING_QUALITY_PGRM", label: "Do you have a keeping quality or retention program? (y/n)", answer: "", source: "PDF" },
  // { key: "QA_TEST", label: "Is in-process quality testing being done? (y/n)", answer: "", source: "PDF" },
  // { key: "QA_TEST_FREQUENCY", label: "What is the frequency of in-process quality testing?", answer: "", source: "PDF" },
  // { key: "DENSITY", label: "Density (Kg Per Lt) - Primary UOM Conversion", answer: "", source: "PDF" },
  // { key: "DEXTROSE_EQUIVALENT", label: "Measure of sweetness level. Test range: 0-100", answer: "", source: "PDF" },
  // { key: "PYROPHOSPHATE", label: "Pyrophosphate content", answer: "", source: "PDF" },
  // { key: "REFRACTIVE_INDEX", label: "Measure of refractive index", answer: "", source: "PDF" },
  // { key: "SCORCHED_PARTICLES", label: "Measurement of scorched particles", answer: "", source: "PDF" },
  // { key: "INSOLUBLE_SUBST", label: "Insoluble substance is the amount of substance that does not dissolve in a solvent.", answer: "", source: "PDF" },
  // { key: "SOLUBILITY", label: "Solubility", answer: "", source: "PDF" },
  // { key: "VISCOSITY_BROOK_TYPE", label: "NEW - Type of Brookfield", answer: "", source: "PDF" },
  // { key: "VISCOSITY_SPINDEL_NU", label: "Spindle Number", answer: "", source: "PDF" },
  // { key: "VISCOSITY_RPM_SPEED", label: "RPM speed", answer: "", source: "PDF" },
  // { key: "PALLET_HOOD_MATRL", label: "Identifies the pallet hood material such as cardboard", answer: "Plastic", source: "PDF" },
  // { key: "C_CULTURE_G_WEIGHT", label: "Culture Weight (g) - 1 packet", answer: "", source: "PDF" },
  // { key: "ALLERGEN_CRUSTCA_LVL", label: "Crustacean shellfish amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_CRUSTCA_SRC", label: "Crustacean shellfish - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_EGG_LVL", label: "Egg products or egg derivatives amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_EGG_SRC", label: "Egg products or egg derivatives - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_FISH_LVL", label: "Fish amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_FISH_SRC", label: "Fish - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_DAIRY_LVL", label: "Dairy products or dairy derivatives amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_DAIRY_SRC", label: "Dairy products or dairy derivatives - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_PEANUTS_LVL", label: "Peanut amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_PEANUTS_SRC", label: "Peanut - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_SESAME_LVL", label: "Sesame seeds amount/100g?", answer: "", source: "PDF" },
  // { key: "ALLERGEN_SOYPROD_LVL", label: "Soy products & hydrolysates amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_SOYPROD_SRC", label: "Soy products & hydrolysates - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_SOY_CCNUT", label: "If soybean or coconut oil is present, is soybean oil and/or coconut oil NOT highly refined? (refined, bleached and deodorized)", answer: "", source: "PDF" },
  // { key: "ALLERGEN_TREENUT_LVL", label: "Treenut or nut derivatives (includes coconut and/or coconut oil) amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_TREENUT_SRC", label: "Treenut - source of", answer: "", source: "PDF" },
  // { key: "ALLERGEN_WHEAT_LVL", label: "Wheat products and hydrolysates amount/100g", answer: "", source: "PDF" },
  // { key: "ALLERGEN_WHEAT_SRC", label: "Wheat Products And Hydrolysates - source of", answer: "", source: "PDF" },
  // { key: "CARAMEL_COLOR_CLASS", label: "If caramel color is present, identity the class", answer: "", source: "PDF" },
  // { key: "CARAMEL_METH_LVL", label: "If class III or IV, indicate the level of 4-Methylimidazole", answer: "", source: "PDF" },
  // { key: "SENS_GLUTEN_LVL", label: "Gluten (from wheat, spelt, kamut, triticale, oats, rye and / or barley) level", answer: "", source: "PDF" },
  // { key: "SENS_SRC_SEED", label: "If seeds or seed derivatives present, identify the source", answer: "", source: "PDF" },
  // { key: "SENS_SRC_HERB", label: "If herb or spices are present, identity the source", answer: "", source: "PDF" },
  // { key: "SENS_PALM_SUSTAINABL", label: "Does palm oil/derivative come form a sustainable source?", answer: "", source: "PDF" },
  // { key: "SENS_PALM_SUS_SOURCE", label: "If Yes, what RSPO supply chain method(s) is used.", answer: "", source: "PDF" },
  // { key: "SENS_PALM_SUS_OPTION", label: "If No, is a sustainable sourcing option availabel?", answer: "", source: "PDF" },
  // { key: "SOURCE_SULFITE", label: "If Sulfites, sulfur dioxide, sodium (bi)-sulfate are present, what is the source?", answer: "", source: "PDF" },
  // { key: "SENS_SULFITE_LVL", label: "If sulfites, sulfur dioxide, sodium (bi)-sulfate are present, what is the level?", answer: "", source: "PDF" },
  // { key: "ASH", label: "Ash content", answer: "0.189", source: "PDF" },
  // { key: "CASEIN", label: "Casein content", answer: "0", source: "PDF" },
  // { key: "FAT_MILK", label: "Milkfat content", answer: "0", source: "PDF" },
  // { key: "FDM", label: "Fat in dry matter", answer: "", source: "PDF" },
  // { key: "LACTOSE", label: "Lactose content", answer: "0", source: "PDF" },
  // { key: "MELTING_POINT", label: "Melting point", answer: "", source: "PDF" },
  // { key: "MELT_TEMP_F", label: "Melt temperature °C", answer: "", source: "PDF" },
  // { key: "MELT_TEMP_C", label: "Melt temperature", answer: "", source: "PDF" },
  // { key: "METALS_HEAVY", label: "Heavy metals content", answer: "", source: "PDF" },
  // { key: "LEAD", label: "Measure of the lead content", answer: "", source: "PDF" },
  // { key: "NORBIXIN", label: "Norbixin - color concentration", answer: "", source: "PDF" },
  // { key: "NPN", label: "Non protein nitrogen content", answer: "", source: "PDF" },
  // { key: "PEROXIDE", label: "Peroxide value - a measure of rancidity", answer: "", source: "PDF" },
  // { key: "AFLATOXIN", label: "Aflatoxin - measure of the toxic chemical metabolites produced by Aspergillus molds", answer: "", source: "PDF" },
  // { key: "LOSS_ON_IGNT", label: "The mass loss after heating to a specific temperature allowing volatile substances to escape", answer: "", source: "PDF" },
  // { key: "RESIDUE_ON_IGNT", label: "Measures the amount of residual substance not volatilized", answer: "", source: "PDF" },
  // { key: "PROTEASE_ACTIVITY", label: "Protease activity - measure of protein breakdown", answer: "", source: "PDF" },
  // { key: "ENZYME_ACTIVITY", label: "Measure of the activity of an enzyme", answer: "", source: "PDF" },
  // { key: "PURITY", label: "Purity - assay, percent pure", answer: "", source: "PDF" },
  // { key: "SOLIDS_MILK_NONFAT", label: "Milk solids nonfat (MSNF) content", answer: "0", source: "PDF" },
  // { key: "SOLIDS_MILK", label: "Milk Solids", answer: "0", source: "PDF" },
  // { key: "STABILIZER_AMOUNT", label: "Stabilizer content", answer: "0", source: "PDF" },
  // { key: "SORBIC_ACID", label: "Sorbic acid content", answer: "0", source: "PDF" },
  // { key: "TITRATABLE_ACIDITY", label: "Measure of titratable acidity", answer: "", source: "PDF" },
  // { key: "WHEY_PROTEIN", label: "Whey protein content", answer: "0", source: "PDF" },
  // { key: "WPN", label: "Whey protein nitrogen content", answer: "", source: "PDF" },
  // { key: "C_SUPPLIER_MIRCO_COM", label: "If no, please state your specificaitons", answer: "", source: "PDF" },
  // { key: "MICRO_LISTERIA", label: "Listeria present? (positive / negative)", answer: "NEGATIVE", source: "PDF" },
  // { key: "MICRO_SALMONELLA", label: "Salmonella present? (positive / negative)", answer: "NEGATIVE", source: "PDF" },
  // { key: "MICRO_STPH_AUREUS", label: "Indicates the maximum acceptable level of Staphylococcus aureus", answer: "", source: "PDF" },
  // { key: "MICRO_YEAST", label: "Indicates the maximum acceptable level of yeast", answer: "9", source: "PDF" },
  // { key: "MICRO_MOLD", label: "Identifies the maximum acceptable level of mold", answer: "9", source: "PDF" },
  // { key: "MICRO_ENTEROTOXIN", label: "Enterotoxin present? (yes/no)", answer: "", source: "PDF" },
  // { key: "MICRO_PLATE_C", label: "Indicates the maximum acceptable level of standard plate count", answer: "999", source: "PDF" },
  // { key: "MICRO_COLIFORM", label: "Identifies the maximum acceptable level of coliform", answer: "9", source: "PDF" },
  // { key: "MICRO_HLB", label: "Identifies the maximum acceptable level of heterofermentative Lactobacilli", answer: "", source: "PDF" },
  // { key: "HETEROTROPHS", label: "Measure of Heterotrophic bacteria", answer: "", source: "PDF" },
  // { key: "COLOR_NCI", label: "NCI color score range. Applies to cheese and plain CC formulas.", answer: "", source: "PDF" },
  // { key: "HUNTER_L_COLOR", label: "Hunter L - measure of the color lightness or darkness", answer: "", source: "PDF" },
  // { key: "HUNTER_A_COLOR", label: "Hunter A - measure of the color greeness or redness", answer: "", source: "PDF" },
  // { key: "HUNTER_B_COLOR", label: "Hunter B - measure of the color blueness or yellowness", answer: "", source: "PDF" },
  // { key: "KOSHER_QUALIFIES", label: "Can item be Kosher certified? (y/n)", answer: "", source: "PDF" },
  // { key: "ORGANIC_PCT_LEVEL", label: "Percent of the product which is certified organic. If the product doesn’t contain Organic, the % will be 0.", answer: "", source: "PDF" },
  // { key: "ORGANIC_CERT_AGENCY", label: "Organic certification agency name", answer: "", source: "PDF" },
  // { key: "RBST_FREE", label: "Is this item rBST free? (y/n)", answer: "Yes", source: "PDF" },
  // { key: "VEGETARIAN_TYPE", label: "If the item is classified as vegetarian, select the vegetarian type.", answer: "Vegan (no aminal products including honey)", source: "PDF" },
  // { key: "GMO - follow - REMOVE QUESTION", label: "Contains or made from genetically modified organisms? (y/n)", answer: "", source: "PDF" },
  // { key: "PROP_65_CHEMICAL", label: "If yes, what is the chemical", answer: "", source: "PDF" },
  // { key: "TRIGGER_PRO_65", label: "Based on intended standard usage levels in our finished products – would it trigger prop 65 warning? (y/n)", answer: "", source: "PDF" },
];


/** 👉  NEW: build starter sheet once, reuse everywhere */
export const QUESTIONS_CSV = [
  'ID,Question,Answer,Source',                                     // header row
  ...QUESTIONS.map((q) => `${q.key},"${q.label.replace(/"/g, '""')}","${q.answer.replace(/"/g, '""')}",${q.source}`)
].join('\n');